---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: blue
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 10s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./clusters/base
  prune: true
  timeout: 5m
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: duah-system
  name: duah-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-environment-config
data:
  ingress-public-ip: 35.228.42.110
  rtmp-input-public-ip: 34.88.169.119
