---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: duah-admin-image-repo
  namespace: duah-apps
spec:
  interval: 5m
  image: ghcr.io/denuafhaengige/duah-admin
  secretRef:
    name: duah-ghcr-pull-secret
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: duah-admin-image-policy
  namespace: duah-apps
spec:
  imageRepositoryRef:
    name: image-repo
  filterTags:
    pattern: '^master-[a-f0-9]+-(?P<ts>[0-9]+)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
