apiVersion: apps/v1
kind: Deployment
metadata:
  name: duah-facebook-api-dep
  namespace: duah-apps
  labels:
    app: duah-facebook-api
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: duah-facebook-api
  template:
    metadata:
      labels:
        app: duah-facebook-api
    spec:
      containers:
      - name: duah-facebook
        image: ghcr.io/denuafhaengige/duah-facebook:master-32f3156-1646429584 # {"$imagepolicy": "duah-apps:duah-facebook-image-policy"}
        args:
        - "--mode"
        - "api"
        imagePullPolicy: IfNotPresent
        env:
        - name: DUAH_LISTENING_PORT
          valueFrom:
            configMapKeyRef:
              name: duah-shared-conf
              key: http-listening-port
        - name: DUAH_HTTP_LISTENING_PORT
          valueFrom:
            configMapKeyRef:
              name: duah-shared-conf
              key: http-listening-port
        - name: DUAH_REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: duah-shared-conf
              key: redis-host
        - name: DUAH_FACEBOOK_PAGE_ID
          valueFrom:
            configMapKeyRef:
              name: duah-shared-conf
              key: facebook-page-id
        - name: DUAH_FACEBOOK_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: duah-shared-secret
              key: facebook-access-token
        - name: DUAH_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: duah-shared-secret
              key: redis-password
        - name: DUAH_APP_INSIGHTS_I_KEY
          valueFrom:
            configMapKeyRef:
              name: duah-shared-conf
              key: application-insights-instrumentation-key
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        - name: health
          containerPort: 9090
          protocol: TCP
        resources:
          limits:
            cpu: 32m
            memory: 64Mi
          requests:
            cpu: 16m
            memory: 32Mi
        livenessProbe:
          httpGet:
            path: /healthz/live
            port: health
          failureThreshold: 3
          periodSeconds: 10
          initialDelaySeconds: 30
        readinessProbe:
          httpGet:
            path: /healthz/ready
            port: health
          failureThreshold: 3
          periodSeconds: 10
          initialDelaySeconds: 30
