apiVersion: v1
kind: Service
metadata:
  name: duah-facebook-api-svc
  namespace: duah-apps
  labels:
    app: duah-facebook-api
spec:
  type: ClusterIP
  selector:
    app: duah-facebook-api
  ports:
  - name: http
    port: 80
    protocol: TCP
