apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: duah-system
spec:
  interval: 1h0m0s
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: duah-system
spec:
  chart:
    spec:
      chart: cert-manager
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cert-manager
      version: '>=1.7.1'
  install:
    crds: Create
  interval: 1h0m0s
  releaseName: cert-manager
  targetNamespace: duah-system
  upgrade:
    crds: CreateReplace
  values:
    installCRDs: true
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: letsencrypt-prod
  namespace: duah-system
spec:
  encryptedData:
    tls.key: AgAr+8c0GtOhOzARNZdu14lrMHdSYy9sN6V2HeFynqftm2xbvJ1fIMqWUMwbyln91KmfNfdTlHScDMHhx8ga/0J9Ed1og6ZMEalzErZtOfNbOFFEs4lO3w8emh+b7QUpM5u7DUPXWty3HUh/N+bIsqKvHiD4WiRbtUB02oGA7KZDWlYcGxnQecJGRnTc5iX4RGrydXY7p5tRiOgzp9a0jfi/aNOM5dw/d9Hs+8f5OiInkif2PVAobqOQaySQrpyOEiKu9iNENuhdIbJrvy85fP6jLBNLrEY/R8tCQPh/ZiH1ibAS/aRtGInVShBvlj7Ac4+GuWZBKr/AwtM5gMLsr26t0Q+L8Ni5nJ6f/IONv02ekz6Ywne32JWlBSg4zpjk1l4+Vvihg/mmdtYtJpZ3cstrRae67XZtEcTQr/shL5smFQM56R0FYrAMDs3e5oyF2voVPA5NSiw2VAVWYy59mBUaP3XUfv38KMsdWwTB1eqH0Dzp9Fn8P3NF3YfBurg0EgO9eimfopN21bf9kglblmIUw4CQeD2hrKeJJ1b0LKEDPQPfxfEH4rubsxPfFnL4MfXZmXRtd9zTx6J1hW312hm1gIRWY5s/PsdP6pAAwRRkG23f1LoWdpsxP/sSwyAN7hASoq+75zyBcKQAAaab0HrTdMvDMM9IT6K9x2Way5oztu6mM3o5tWPq0QCj/3CVHg0afG04F8/3ve2bSw7CMgXAZyAPE2fZjpXgKHHaEIN0vdc5dQCyp8vu/wU/FP7dnb4DgQhboyGdF23eDQgBj+tvdL6qbRa8ornu4yqkSeEd3fhcxCVs1t3zFglOwN6/NUIESO3XX8hCS3bx9maBVU9beAUR8oWEtlKeZcoxIPH3uoe5PTMQSIG5J4RlmplnqCOnyHrK+/VwX3bQKF1z3oIOPVoOlb/VwlxfK9UVPtQsH3zxLF3v1UT1fN+30M3VrMeE8jfDcGnz6ADJpXQIM0oXGGbHgy6yn+Zu9aZbbLz3xvi/+sKRgtH93sJT8MN2u0L9JnwB76/eGqCErTfm1q/42feCmdlM5RAZ5ZMJTM4Y4kJewUYz1rdkTzxFBjZ/9bu4nYqznsbQjAZtXzJC7klFGdlEcYo0EKtlQ0GZ5UqCzZ3KihyhSCHP+Olh1CxyUwGaNt/ki+T95dAGHSanf1RDYMAhKucTAPnvJK8oHk8+cgLBRaGKcRjH3kDeNB25Dl/ws0dJQNQtl1g5jVaRyx/x7PheTbKKvl43u/cIvnwRoJkkzqxCenmik8PKAh6mhVy+iSMsNAjkljVTQ8UTHstQ3TTcFY6MXDK4YZxwbPjncfTafeXXHo7xu39bFlj+7md2N9QpRObZ0CsKg02n7L8JMEzIg2zEttf3eju/8r9ojaGx8k+xoFGNMSCWGFXGFFwPWgtnxTs8tfBRfm10aHw2z0bC5DJI5foFTRPvczflq3yDpqNVmtDGaKkCXy0gagJBNxnoAtwNMJxrjp1tsUsOxE8n84RxN59YTwvWpU458lo+TCZrbRckL7SZni9INoSVWCS03agC12Flou+uqHFlGm6xePZ+msYGNKPdRxj1gkCnK7E7eDt8oLF1UFqbRIVJtLD93YmRKbZtAy12H/4GjT0UWdGRRduHPNKbTOtRFuaHen2JdEmDSAXqJT7OyKadvtHCakCOZxLN3YTpSq7zgboAQHz0tlZhhjl1s2AJwrCfMWFxi4Zcwx2Nsc40Xh93yn90iPWNengnPV5WFkRLbJsoPiSvUW2r/g/4de+CKAYBU/ReLCy8pXsrsw5swYxzsszqLACo5jF8tlSSNTwnASfUoxdJGJHtezMoudZGHw5vhtDoyLOJFulzpxLO9u6/9ELUPJ5pXZQ6mXPOgsKiA5U/O7Cz4rreNJZWvZizjwKBGf5fWBVpcT1PHKywPoIy+4WWbOWNTen8e3i1CUg3HdWU+m3G3UZKV/WK/TgdRXflErX5a89uEKZsqFC3Uzk9NCH9++IFR8IWj6ySZpw0J9GaEZWNP2q1ray7W+wfgQK3Rb/Zljl6o/vs7qJ8EPpFvb/C+kCFri7h4uxT7q137NPZrZREJG7kz0LphZzYh06GovBox/9C6XFDTnhEPeE2s7t6HoShSWOZWffnzxIwdhOTBgPayPSDY8QDNNlVoE+uNJxwIhAKRmozyiSAwWxHrhgXkqwPdCFTTKrWaYKoacYx+O4SBPJBIVQ4cBW2iXCiTFWcLjbFlxdKxZlm+zL/iAmXAcNxpO4NsnrXKKFq+/uUHhmROZdAhktDuJ7/ZxY2KG0O6iJlV3A9WhvESLvqKPu0THoFmVBxdrYbK65+fBIuG+KgJ9hWImXqZqEjHtpYEA/H6Ra5JIcZ86HsnnmqsJQOQou/pD419nPQQOMOSZr2sB0SCraVIDs04mHJ+UjSrQCwfLI4+nrrHQIRAs26yikKpjSi0+5GzGnSyUuZcheqbfoXdRxbdi4U/u4Xi3oYVHn3SAA1j8SJR8b+OVJscp30Dz3oSOCPuCIqx7T/LsiiyqkhH1xy8MVUKZlg4Ai+a95+0rxM41mU/BcQ5WrFRqFdrr3JkHlpP63OHLpwrFDc0lktWAWF1U6lw2fsDS/XO1ybCpZpQ/IeBMZGbflVWMh3O1agW5/pSb+E/pj1RJ7KKBkTyWAcB/wcRW4D8HMAkxWLVAdx6o3ztH2Gd0EcJlbiHmy4k8DRG6QxiKRHLUCGMpgsuOl3HVun1i7yD51JFzldw0KGTB6yY8nqPYDDCAgUcA9V6YGH0q5pRTMYvw2wK23KsFmF2XJdQc/oqMrkK0NnFYUuUCMTkbJbwoPAtaWHtk/TDUgxcG0LIAeb5eELhJvxUuyXE3cQ8ALzMia/LH1F0MlueUZRHQT7BYipve5xa34WUy+k+gLwlBWbqYYpRuK32n+hcsPAF20qgwQwc0JSIzvAWqzazExlSA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: letsencrypt-prod
      namespace: duah-system
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: duah-dns-sa-key
  namespace: duah-system
spec:
  encryptedData:
    key: AgAiJTaSeDv82TFRltzxvFOaLwgfhBai+0Fk/waMi18TbJ1tYbBoM8wZhuk75hbIgBjmrfO/6q14aTdKSIvH58kWfStJOOyFdmte/MovXVNOX8JMmD3pU6GyB8bLdPnWJMPF9ORKudzvnEiPVFnZX6CQmttMN1cPXsb95oP579NBQ/RSBvNY9nBLeUv2rWyvHq2nJF+uS4E+s5j3uH5PLrw7X7AZBvF5KeCmFMQDpag0NnLa7k0kPOFRyMoqoVQliGcql/Bc31YW9ZTKxtW3fw08gVj0RlXspAlEWvWjhyzwX0x8MTx9blvnH1Oj5jV12vgNB32PswkDNz+eazYKv6ul3alyJsqoZCnyhgJRGp14FzEl4FvM+6+zVMnGbou4digqkTlyDJm3DXV9Y+l0n09IuKxoGy/z+KsZrkFtBGU8zDmI0SLvTgr6ILxVzk2Dn9uQ2DkuSinSgXJqMKuilvSYbBAa+ZIuETPS94BOC12NyRU/0pI4JYggXgTks2le3EgLFECV2+uEVWlOmChWtoJlIMStROTtL+sYQBkh7seiKfr9oIXUXBYtDVQYjwrchXg144fijE/TMRoU3Dbm/ubm/WN7i81gY3nwG0NgdnHSYve8vjgZYTitJm15lZlcYqFHwftCIlOrfT8uceSp9Vv90jwJcktVYKgtL+ZEhSFAnjDW9RsCDo9sE0HyvyEyXZn3uPdSCTdQb7Bfoyvgy61PleE4JNMaxcLNwnZZbUS1mMI+y5BzknZOfuoD7MpVWFHisvHBqwC5OeBT1FpwXSDlyCY3HOMErLjn28y4UFdDdowfWDf6RoiDooa0bufc3VPP7h9Wa6WqXtC8F35Br/clgwUa4nrg7HmjMf7g7knPoWr928ucv+VL7hlVMR8LBUkuhrIRJT/oy1kcIVJzNTLLQu/Swfehu0QCvn7DVH6bUgsB1uUGZXUJZsncLXmZgF5D6RJt4A79f1uYyCGOXwsUGBe9AeXKxMYQ5zKKxC0/PrxQeMXiIkzz/ZQs5iAai2PlW/F9ZR+WOAWSqHp1eGLEW3/BCpXcWX6sDD95KQMZ6kcQsdtLuuB3IFP5WPqV/B6iQV5bDRHu+zYChi6fKyaqoMddPc/+FzHETWYGsI/azcC61kpypyXqnxpFUKsYPDZFLYAXaqGKgBc7oD2gUzOyL65jB8moBPNIvNv653hZfYWDeL4nfqyg+Xdixx+WZdkVgDI1jHGKIvY7e2OqYXmTTz/S/nGBWpZxRg+8T6w3xm8BtKbdF0Na/U9bH+bnecghS7aZigdLE5OIhn7GqwdBab0KTsyX+yVXRSrmcR0xdKrAOSkP5KN6WqzjUrRqClHwNgANMgoLEOVOlCEFTJ9v6yOL048F+MAl+zH8kcDRA+FzYDssQBBlkgRpWbgIPAR4JkU3NPG5OQD70x1kikHLM0dMkRXiDqlw7fAO9cn7lln6f+fMc8mLH72JesxXRp/u8yozTO1pk8QrpnDOMhODb2eMSWYLZ5psDpABP9vlMYNdQshvBgVLoEcqF/HBClM/Xs2KCxGizuB5KJTXVo5vPP6C5gfdxLPF0sxz+MFA8OX5tYPDF9WTRZEQuoG7799+nWgA1WEfW80Pgg5DaBBVQI4QkXIWebEPjGjUd3MzbV7abzyPbATfgDXrimnl3JSOeT5EeUVduFS+oj+Df7UczIbdHt7jeahMb4FShw62ikJCSOSPN85BemDEOQgTtIhnqVncBYN2Q3nzeYbE55LaKSgxwxfzPrBitO/FtfeuMYxG5pBihIYBFCQNVHsSJcAOSYksIU1LblT7eYTJqW25kOUt75jCsAyhTUzZuoXoUKnW/apuGHan1KpJl5W61gHAr7eHusfbztqdejQbCRuYZISZHYrK4XSz1TZOC1lUQfGIjx4ldkxQNRJs410Nr/rRMqxEQlnq27G91E2i+ovCsjn7XKsBPZCZaF34m8E2FH6hM+8QKRquHOVqDTfzJu0Rf2hNS/qiM6bE5EuSC8ifigovf7Ezg7Ey0+njuf4u3pa562nXgl7giU4wvHYHgW+yksBSetNus0mN3YOK3Lp2+7hI2Pvz3T8OfljtA5AaNrOgFA51PyA9bvU+yBDgp/u6oPvw7GoEhrhqB9vQwoHocooXUMy/oUDkC18J1363iOCU8TItX1SyreUZedAMalI6vmJ5ujWx5cahj8B3ePR3Xc0B+blF001Gs3ehI5wLeywodI5HghF8ArtXrpC8ATQuggMfT7V3VHy7P03OGmkzKfl74+ZK5UAsLF/zJzU1CxpuSL0iUpd+rPyZgYx9RNGAiNwQ6JNAq6Xi9J7D2JwY5WIMu9RbOudVUDNrjtmSjccmVpaBUuFxk+oGkucLr6e0jEuCYsHGrPD3Yd2qqf+YFsjvrYt+WWziRbIODhBXckSkvBEyhp8/WmhHPLyC+VQYr2zK+uAA4khoHJEEHUnujc+03REcEUA8/LFlnJXgNVVO3bvY+fJSh4ataL9n7unXKCU1eiDt39r+6vpor6+LnT3cf/YzwccfZtiR555zvrKgAcPH+E2RnCnFWj2A1PjJc7MXAwTuEGVlfenLzIoAMmy2+DCRa9Fyr0SHvtjdE4JOnEc0c3P6nfc/532rGammwNeStu3k+81frJi3ddaqBx/nJGhoF9Hl6l3Yzt1IyAK+6QyVd2FdB+1Cp1zQ4flo/uRzuSWgBsgX8KM8xeLdvc71cy1GVMGFpy9nerH7xDWYtiuA5i+aI4U+WXilvBYoabih+6b2Htxjx9nDoqJmWR13j4kUDLa/V/B4STJjwy2SIV1Fx179dTOqFJSZc7biUHzKoATvyc3dUSLwgjhVHs0S5PUTbV6VEbRNsmbkDAijYUITBl/NeBjf9kFzF7Md48yGa3r+BxBvJTnJOkT/LbvfQMlNtJkyq29mbINItSn/3TNwCtH+eJb9rIIeSKxEMlucIeWCicFhds/+vrrrs1QiTg1Nyc0L4sSOXFrotuZLFa/nGt2XU8Q0UfKm8wzRr6Y/9oPbnihfY/1dM9I2+PX024C636L4o6wNpVr1+gSc9w5j3AxQxcLONhpUWUeTJQd3gt31WjOw3itRbtEXWX3cP177iOyWScIKHzZEyzyfrxlVNo/uC4dbM7hYM0s35Qp9rJERgVLCYxE8sL088ubq8JOCuhjUZTTxGgB3/xewO++H2+Y52zl9Xe7Un+y1sBQ0GbA9hWNN0oPLwOsUCyqu8Tpfo1nWCbEAWNm5qbyQMz5SheNj/49bbhajBGXIGd/q+zs4uAooxkJcpm2+iCBSZd2nlIqdDn6RO8oSWpJE0V8D5/QLu/F5Y0eWVgjCNLe+DNOvsMLnCdtXn1cO8v5EhzKngJPNH+DfBrOAzzpd0/x5RucLYQSEHUSTIuZNMoMH4k2lLOpJi7wuhat9RGN5nkTHyWVR4dumGirqE/S614ABZAH6IWUENCMq8E+UnscPxOHFhNqQJWtLE8xtXtiljYo01feoju5YZ3UuXFupBh9WmCkT0oVDg6wpARiVwOdYPrmZinjES0nZxY/7OfIV/0tfz8Fbhq9tBxFiYos5nv2g6vwJ4YDDZToX3WKCeG/xumuaNx2o4hliYuNrDia5QkC7ierJpna2etc5qH4TCGV08Vvd5B3yT12EYGcCLC8yfe3oOg9Uns3J/ICGkun0aa4urZ+QVZWr62f+PXMyiGd+SQL7Ttk4G5RdxZp1fsb20+5QO+/rNv0insSaIa84drO0boRSQ9bBRe3DvzddDMYYWca0BMYZlBo+UAi7K5nwAx1cWVshLB1uzIA=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: duah-dns-sa-key
      namespace: duah-system
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-http-prod
  labels:
    name: letsencrypt-http-prod
spec:
  acme:
    email: rasmus@hummelmose.dk
    disableAccountKeyGeneration: true
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns-prod
  labels:
    name: letsencrypt-dns-prod
spec:
  acme:
    email: rasmus@hummelmose.dk
    disableAccountKeyGeneration: true
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        cloudDNS:
          project: denuafhaengige
          serviceAccountSecretRef:
            name: duah-dns-sa-key
            key: key
