apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: nginx-ingress
  namespace: duah-system
spec:
  interval: 1h0m0s
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: duah-system
spec:
  chart:
    spec:
      chart: ingress-nginx
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: nginx-ingress
      version: '>=1.7.1'
  install:
    crds: Create
  interval: 1h0m0s
  releaseName: nginx-ingress
  targetNamespace: duah-system
  upgrade:
    crds: CreateReplace
  values:
    controller:
      watchIngressWithoutClass: true
      ingressClassResource:
        default: true
      service:
        loadBalancerIP: "34.88.10.160"
---
