apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: redis
  namespace: duah-apps
spec:
  interval: 1h0m0s
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: duah-apps
spec:
  chart:
    spec:
      chart: redis
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: redis
      version: '>=16.4.5'
  install:
    crds: Create
  interval: 1h0m0s
  releaseName: redis
  targetNamespace: duah-apps
  upgrade:
    crds: CreateReplace
  values:
    auth:
      enabled: false
    architecture: standalone
---
