# apiVersion: source.toolkit.fluxcd.io/v1beta1
# kind: HelmRepository
# metadata:
#   name: velero
#   namespace: duah-system
# spec:
#   interval: 1h0m0s
#   url: https://vmware-tanzu.github.io/helm-charts
# ---
# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: sealed-secrets
#   namespace: duah-system
# spec:
#   chart:
#     spec:
#       chart: velero
#       reconcileStrategy: ChartVersion
#       sourceRef:
#         kind: HelmRepository
#         name: velero
#       version: '>=1.8.0'
#   install:
#     crds: Create
#   interval: 1h0m0s
#   releaseName: velero
#   targetNamespace: duah-system
#   upgrade:
#     crds: CreateReplace
# ---
