---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns-prod
  labels:
    name: letsencrypt-dns-prod
spec:
  acme:
    email: rasmus@hummelmose.dk
    disableAccountKeyGeneration: true
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        cloudDNS:
          project: denuafhaengige
          serviceAccountSecretRef:
            name: duah-dns-sa-key
            key: key
