---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-http-prod
  labels:
    name: letsencrypt-http-prod
spec:
  acme:
    email: rasmus@hummelmose.dk
    disableAccountKeyGeneration: true
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: nginx
