---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: gcloud-sqlproxy-credentials
  namespace: duah-system
spec:
  interval: 10m
  retryInterval: 10s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./infra/gcloud-sqlproxy/credentials
  prune: true
  wait: true
  timeout: 30s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: gcloud-sqlproxy-installation
  namespace: duah-system
spec:
  dependsOn:
  - name: gcloud-sqlproxy-credentials
  interval: 10m
  retryInterval: 10s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./infra/gcloud-sqlproxy/installation
  prune: true
  wait: true
  timeout: 30s
