---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: duah-vod-dep
  namespace: duah-apps
  labels:
    app: duah-vod
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: duah-vod
  template:
    metadata:
      labels:
        app: duah-vod
    spec:
      containers:
      - name: duah-vod
        image: ghcr.io/denuafhaengige/duah-streaming:sha-22a6595 # {"$imagepolicy": "duah-apps:duah-streaming-image-policy"}
        imagePullPolicy: IfNotPresent
        args:
        - --mode
        - vod
        env:
        - name: DUAH_FILE_STORAGE_PATH
          valueFrom:
            configMapKeyRef:
              name: duah-shared-conf
              key: file-storage-path
        - name: DUAH_REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: duah-shared-conf
              key: redis-host
        - name: DUAH_DATABASE_URI
          valueFrom:
            secretKeyRef:
              name: duah-shared-secret
              key: database-uri
        - name: DUAH_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: duah-shared-secret
              key: redis-password
        - name: DUAH_APP_INSIGHTS_I_KEY
          valueFrom:
            configMapKeyRef:
              name: duah-shared-conf
              key: application-insights-instrumentation-key
        - name: DUAH_TEMP_STORAGE_PATH
          valueFrom:
            configMapKeyRef:
              name: duah-shared-conf
              key: temp-storage-path
        - name: DUAH_STREAMING_NGINX_ACCESS_LOG_PATH
          valueFrom:
            configMapKeyRef:
              name: duah-shared-conf
              key: streaming-nginx-access-log-path
        - name: DUAH_STREAMING_NGINX_ERROR_LOG_PATH
          valueFrom:
            configMapKeyRef:
              name: duah-shared-conf
              key: streaming-nginx-error-log-path
        - name: DUAH_STREAMING_NGINX_TAIL_LOG_FILES
          valueFrom:
            configMapKeyRef:
              name: duah-shared-conf
              key: streaming-nginx-tail-log-files
        - name: DUAH_STREAMING_NGINX_LOG_LEVEL
          value: "info"
        - name: DUAH_STREAMING_NGINX_MIME_TYPES_PATH
          valueFrom:
            configMapKeyRef:
              name: duah-shared-conf
              key: streaming-nginx-mime-types-path
        - name: DUAH_STREAMING_VOD_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: duah-shared-conf
              key: streaming-vod-base-url
        volumeMounts:
        - name: duah-shared-storage
          mountPath: /mnt/shared-storage
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        - name: health
          containerPort: 9090
          protocol: TCP
        resources:
          limits:
            cpu: 1024m
            memory: 512Mi
          requests:
            cpu: 256m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /healthz/live
            port: health
          failureThreshold: 3
          periodSeconds: 10
          initialDelaySeconds: 30
        readinessProbe:
          httpGet:
            path: /healthz/ready
            port: health
          failureThreshold: 3
          periodSeconds: 10
          initialDelaySeconds: 30
      volumes:
      - name: duah-shared-storage
        persistentVolumeClaim:
          claimName: duah-shared-storage-pvc
