apiVersion: apps/v1
kind: Deployment
metadata:
  name: duah-rtmp-input-dep
  namespace: duah-apps
  labels:
    app: duah-rtmp-input
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: duah-rtmp-input
  template:
    metadata:
      labels:
        app: duah-rtmp-input
    spec:
      containers:
      - name: duah-rtmp-input
        image: ghcr.io/denuafhaengige/duah-streaming:master-e6b1834-1646433258 # {"$imagepolicy": "duah-apps:duah-streaming-image-policy"}
        imagePullPolicy: IfNotPresent
        args:
        - --mode
        - rtmp-input
        env:
        - name: DUAH_STREAMING_SEGMENT_RECORDINGS_FOLDER_PATH
          valueFrom:
            configMapKeyRef:
              name: duah-shared-conf
              key: streaming-segment-recordings-file-path
        - name: DUAH_STREAMING_SINGLE_FILE_RECORDING_FOLDER_PATH
          valueFrom:
            configMapKeyRef:
              name: duah-shared-conf
              key: streaming-single-file-recordings-file-path
        - name: DUAH_FILE_STORAGE_PATH
          valueFrom:
            configMapKeyRef:
              name: duah-shared-conf
              key: file-storage-path
        - name: DUAH_TEMP_STORAGE_PATH
          valueFrom:
            configMapKeyRef:
              name: duah-shared-conf
              key: temp-storage-path
        - name: DUAH_REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: duah-shared-conf
              key: redis-host
        - name: DUAH_DATABASE_URI
          valueFrom:
            secretKeyRef:
              name: duah-shared-secret
              key: database-uri
        - name: DUAH_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: duah-shared-secret
              key: redis-password
        - name: DUAH_APP_INSIGHTS_I_KEY
          valueFrom:
            configMapKeyRef:
              name: duah-shared-conf
              key: application-insights-instrumentation-key
        - name: DUAH_STREAMING_NGINX_ACCESS_LOG_PATH
          valueFrom:
            configMapKeyRef:
              name: duah-shared-conf
              key: streaming-nginx-access-log-path
        - name: DUAH_STREAMING_NGINX_ERROR_LOG_PATH
          valueFrom:
            configMapKeyRef:
              name: duah-shared-conf
              key: streaming-nginx-error-log-path
        - name: DUAH_STREAMING_NGINX_TAIL_LOG_FILES
          valueFrom:
            configMapKeyRef:
              name: duah-shared-conf
              key: streaming-nginx-tail-log-files
        - name: DUAH_STREAMING_NGINX_LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: duah-shared-conf
              key: streaming-nginx-log-level
        - name: DUAH_STREAMING_ICECAST_SOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: duah-shared-secret
              key: streaming-icecast-source-password
        - name: DUAH_STREAMING_ICECAST_MASTER_HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: duah-shared-conf
              key: streaming-icecast-master-hostname
        - name: DUAH_SHARED_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: duah-shared-secret
              key: shared-encryption-key
        volumeMounts:
        - name: duah-shared-storage
          mountPath: /mnt/shared-storage
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        - name: rtmp
          containerPort: 1935
          protocol: TCP
        - name: health
          containerPort: 9090
          protocol: TCP
        resources:
          limits:
            cpu: 8048m
            memory: 2048Mi
          requests:
            cpu: 2024m
            memory: 1024Mi
        livenessProbe:
          httpGet:
            path: /healthz/live
            port: health
          failureThreshold: 3
          periodSeconds: 10
          initialDelaySeconds: 30
        readinessProbe:
          httpGet:
            path: /healthz/ready
            port: health
          failureThreshold: 3
          periodSeconds: 10
          initialDelaySeconds: 30
      volumes:
      - name: duah-shared-storage
        persistentVolumeClaim:
          claimName: duah-shared-storage-pvc
