---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-prereqs
  namespace: duah-system
spec:
  dependsOn:
  - name: infrastructure
  interval: 10m
  retryInterval: 10s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./apps-prereqs
  prune: true
  wait: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: duah-system
spec:
  dependsOn:
  - name: apps-prereqs
  interval: 10m
  retryInterval: 10s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./apps
  prune: true
  wait: true
  timeout: 30s
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-environment-config
        namespace: flux-system
