apiVersion: v1
kind: Service
metadata:
  name: duah-stream-front-svc
  namespace: duah-apps
  labels:
    app: duah-stream-front
spec:
  type: ClusterIP
  selector:
    app: duah-stream-front
  ports:
  - name: http
    port: 80
    protocol: TCP
