apiVersion: v1
kind: Service
metadata:
  name: duah-vod-svc
  namespace: duah-apps
  labels:
    app: duah-vod
spec:
  type: ClusterIP
  selector:
    app: duah-vod
  ports:
  - name: http
    port: 80
    protocol: TCP
