---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: green
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 10s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./clusters/base
  prune: true
  timeout: 5m
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: duah-system
  name: duah-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-environment-config
  namespace: duah-system
data:
  ingress_public_ip: 35.228.27.5
  rtmp_input_public_ip: 34.88.189.185
