---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: green
  namespace: duah-system
spec:
  interval: 10m
  retryInterval: 10s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./clusters/base
  prune: true
  wait: true
  timeout: 5m
  patches:
  - patch: |
      - op: replace
        path: /spec/loadBalancerIP
        value: 34.88.189.185
    target:
      kind: Service
      name: duah-rtmp-input-public-svc
      namespace: duah-apps
  - patch: |
      - op: replace
        path: /spec/values/controller/service/loadBalancerIP
        value: 35.228.27.5
    target:
      kind: HelmRelease
      name: nginx-ingress
      namespace: duah-system
