apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: duah-ghcr-pull-secret
  namespace: duah-apps
spec:
  encryptedData:
    .dockerconfigjson: AgACvwkkCSVdG/vpdbzVyQ0/sKCJNjJ4UgJUSS6xrFA5QuNbIlY8npfke/pe6M84vqCfMPReVcYUbld1MyRrLc14+QJjjIFnUQUJrZ6p4cV/U6biIQVyQeKbvipPmCVv/lACWvMuWUsdy2BZewV2LT1EZheaMKc0KGUofSOhRLMlm4puRRYCYk2Soxdz5jA+XlygkOLfAXqjSlVMKa7/0+fqMlZ78FJAm3/YJx7EJ5jIifd9uAOVi2TfhyC0aQ3+8L7hBYjIp5Ig3TzodYA+qrl8ylVSmGISWZdj+QkX/YaVxBIMLzawlF6syJdll1eiwyUmrBlTSVlEzbzigZm8K12f0xMJLKCxYWYvU/N4cnYAkXMju0dBTgQ+E7Cepc1gbGPnLdZbhTzGsyOJ+tlvdbgm/XGYx0HUwDNDCiVFox+su1mdkT2mK1Z5Jbu9x14O9o2tkk5G/7IE73UPw2vSoH0DB+CGLyBwTJP3kJPGSmXbXAv7TPF6y3+OpkJMhdCcsyycuF272rOkb2MGE4n0lUGjiJvajBYFbu3W4mBnqUT8rpBzyCLOR/jxZnPNWPrDIBi/zUe5KhunZ7yRMCrU+AAaFSOjpBo7VXpbTdf0wOtPYlfz3TU7g7MCm//Ta85DHgc63k0x/+lJElv90tQDn4J2GFhGg+SKmQ0LxVKleQweFJHFG51hX2duYjjD5fcHsfOfRTCELeosgXSTNJNRXBXlM7xCJZBLH9sYuil+1KpndJYDFLpb98J5ZNhzUsgxEYRrRHUW5Ld9cpQAXOJxjdESFFPHu1sdbkhcry8V1Tb3fp4GxEAKjVSGvUa0jf3gSwkBzQDKVG9/VP0=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: duah-ghcr-pull-secret
      namespace: duah-apps
    type: kubernetes.io/dockerconfigjson
