---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: duah-system
spec:
  chart:
    spec:
      chart: redis
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: redis
      version: '>=16.4.5'
  install:
    crds: Create
  interval: 1h0m0s
  releaseName: redis
  targetNamespace: duah-system
  upgrade:
    crds: CreateReplace
  values:
    global:
      storageClass: regional-pd-ssd-storageclass
    auth:
      enabled: false
    architecture: standalone
