apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: duah-system
spec:
  interval: 1h0m0s
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: duah-system
spec:
  chart:
    spec:
      chart: cert-manager
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cert-manager
      version: '>=1.7.1'
  install:
    crds: Create
  interval: 1h0m0s
  releaseName: cert-manager
  targetNamespace: duah-system
  upgrade:
    crds: CreateReplace
  values:
    installCRDs: true
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-http-prod
  labels:
    name: letsencrypt-http-prod
spec:
  acme:
    email: rasmus@hummelmose.dk
    disableAccountKeyGeneration: true
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: letsencrypt-prod
  namespace: duah-system
spec:
  encryptedData:
    tls.key: AgAr+8c0GtOhOzARNZdu14lrMHdSYy9sN6V2HeFynqftm2xbvJ1fIMqWUMwbyln91KmfNfdTlHScDMHhx8ga/0J9Ed1og6ZMEalzErZtOfNbOFFEs4lO3w8emh+b7QUpM5u7DUPXWty3HUh/N+bIsqKvHiD4WiRbtUB02oGA7KZDWlYcGxnQecJGRnTc5iX4RGrydXY7p5tRiOgzp9a0jfi/aNOM5dw/d9Hs+8f5OiInkif2PVAobqOQaySQrpyOEiKu9iNENuhdIbJrvy85fP6jLBNLrEY/R8tCQPh/ZiH1ibAS/aRtGInVShBvlj7Ac4+GuWZBKr/AwtM5gMLsr26t0Q+L8Ni5nJ6f/IONv02ekz6Ywne32JWlBSg4zpjk1l4+Vvihg/mmdtYtJpZ3cstrRae67XZtEcTQr/shL5smFQM56R0FYrAMDs3e5oyF2voVPA5NSiw2VAVWYy59mBUaP3XUfv38KMsdWwTB1eqH0Dzp9Fn8P3NF3YfBurg0EgO9eimfopN21bf9kglblmIUw4CQeD2hrKeJJ1b0LKEDPQPfxfEH4rubsxPfFnL4MfXZmXRtd9zTx6J1hW312hm1gIRWY5s/PsdP6pAAwRRkG23f1LoWdpsxP/sSwyAN7hASoq+75zyBcKQAAaab0HrTdMvDMM9IT6K9x2Way5oztu6mM3o5tWPq0QCj/3CVHg0afG04F8/3ve2bSw7CMgXAZyAPE2fZjpXgKHHaEIN0vdc5dQCyp8vu/wU/FP7dnb4DgQhboyGdF23eDQgBj+tvdL6qbRa8ornu4yqkSeEd3fhcxCVs1t3zFglOwN6/NUIESO3XX8hCS3bx9maBVU9beAUR8oWEtlKeZcoxIPH3uoe5PTMQSIG5J4RlmplnqCOnyHrK+/VwX3bQKF1z3oIOPVoOlb/VwlxfK9UVPtQsH3zxLF3v1UT1fN+30M3VrMeE8jfDcGnz6ADJpXQIM0oXGGbHgy6yn+Zu9aZbbLz3xvi/+sKRgtH93sJT8MN2u0L9JnwB76/eGqCErTfm1q/42feCmdlM5RAZ5ZMJTM4Y4kJewUYz1rdkTzxFBjZ/9bu4nYqznsbQjAZtXzJC7klFGdlEcYo0EKtlQ0GZ5UqCzZ3KihyhSCHP+Olh1CxyUwGaNt/ki+T95dAGHSanf1RDYMAhKucTAPnvJK8oHk8+cgLBRaGKcRjH3kDeNB25Dl/ws0dJQNQtl1g5jVaRyx/x7PheTbKKvl43u/cIvnwRoJkkzqxCenmik8PKAh6mhVy+iSMsNAjkljVTQ8UTHstQ3TTcFY6MXDK4YZxwbPjncfTafeXXHo7xu39bFlj+7md2N9QpRObZ0CsKg02n7L8JMEzIg2zEttf3eju/8r9ojaGx8k+xoFGNMSCWGFXGFFwPWgtnxTs8tfBRfm10aHw2z0bC5DJI5foFTRPvczflq3yDpqNVmtDGaKkCXy0gagJBNxnoAtwNMJxrjp1tsUsOxE8n84RxN59YTwvWpU458lo+TCZrbRckL7SZni9INoSVWCS03agC12Flou+uqHFlGm6xePZ+msYGNKPdRxj1gkCnK7E7eDt8oLF1UFqbRIVJtLD93YmRKbZtAy12H/4GjT0UWdGRRduHPNKbTOtRFuaHen2JdEmDSAXqJT7OyKadvtHCakCOZxLN3YTpSq7zgboAQHz0tlZhhjl1s2AJwrCfMWFxi4Zcwx2Nsc40Xh93yn90iPWNengnPV5WFkRLbJsoPiSvUW2r/g/4de+CKAYBU/ReLCy8pXsrsw5swYxzsszqLACo5jF8tlSSNTwnASfUoxdJGJHtezMoudZGHw5vhtDoyLOJFulzpxLO9u6/9ELUPJ5pXZQ6mXPOgsKiA5U/O7Cz4rreNJZWvZizjwKBGf5fWBVpcT1PHKywPoIy+4WWbOWNTen8e3i1CUg3HdWU+m3G3UZKV/WK/TgdRXflErX5a89uEKZsqFC3Uzk9NCH9++IFR8IWj6ySZpw0J9GaEZWNP2q1ray7W+wfgQK3Rb/Zljl6o/vs7qJ8EPpFvb/C+kCFri7h4uxT7q137NPZrZREJG7kz0LphZzYh06GovBox/9C6XFDTnhEPeE2s7t6HoShSWOZWffnzxIwdhOTBgPayPSDY8QDNNlVoE+uNJxwIhAKRmozyiSAwWxHrhgXkqwPdCFTTKrWaYKoacYx+O4SBPJBIVQ4cBW2iXCiTFWcLjbFlxdKxZlm+zL/iAmXAcNxpO4NsnrXKKFq+/uUHhmROZdAhktDuJ7/ZxY2KG0O6iJlV3A9WhvESLvqKPu0THoFmVBxdrYbK65+fBIuG+KgJ9hWImXqZqEjHtpYEA/H6Ra5JIcZ86HsnnmqsJQOQou/pD419nPQQOMOSZr2sB0SCraVIDs04mHJ+UjSrQCwfLI4+nrrHQIRAs26yikKpjSi0+5GzGnSyUuZcheqbfoXdRxbdi4U/u4Xi3oYVHn3SAA1j8SJR8b+OVJscp30Dz3oSOCPuCIqx7T/LsiiyqkhH1xy8MVUKZlg4Ai+a95+0rxM41mU/BcQ5WrFRqFdrr3JkHlpP63OHLpwrFDc0lktWAWF1U6lw2fsDS/XO1ybCpZpQ/IeBMZGbflVWMh3O1agW5/pSb+E/pj1RJ7KKBkTyWAcB/wcRW4D8HMAkxWLVAdx6o3ztH2Gd0EcJlbiHmy4k8DRG6QxiKRHLUCGMpgsuOl3HVun1i7yD51JFzldw0KGTB6yY8nqPYDDCAgUcA9V6YGH0q5pRTMYvw2wK23KsFmF2XJdQc/oqMrkK0NnFYUuUCMTkbJbwoPAtaWHtk/TDUgxcG0LIAeb5eELhJvxUuyXE3cQ8ALzMia/LH1F0MlueUZRHQT7BYipve5xa34WUy+k+gLwlBWbqYYpRuK32n+hcsPAF20qgwQwc0JSIzvAWqzazExlSA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: letsencrypt-prod
      namespace: duah-system
    type: Opaque
---
