apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: duah-system
spec:
  interval: 1h0m0s
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: duah-system
spec:
  chart:
    spec:
      chart: cert-manager
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cert-manager
      version: '>=1.7.1'
  install:
    crds: Create
  interval: 1h0m0s
  releaseName: sealed-secrets-controller
  targetNamespace: duah-system
  upgrade:
    crds: CreateReplace
  values:
    installCRDs: true
---
