---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: csi-gcs
  namespace: duah-system
spec:
  interval: 1m0s
  ref:
    branch: master
  url: https://github.com/ofek/csi-gcs.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: csi-gcs
  namespace: duah-system
spec:
  interval: 10m0s
  path: ./deploy/overlays/stable-gke/
  prune: true
  sourceRef:
    kind: GitRepository
    name: csi-gcs
