apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - github.com/ofek/csi-gcs/deploy/overlays/stable-gke?ref=v0.8.0
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: DaemonSet
    metadata:
      name: csi-gcs
